### ISSUE TITLE
[discussion] Tags

### ISSUE THREAD

**Issue by dandv** [rolwin100/rolwinreevan_gatsby_blog#1]
Hi, nice starter!

Wanted to start a Discussion (like [this](https://github.com/react-hook-form/react-hook-form/discussions)) but I didn't see it enabled on this repo, sorry for filing an issue :)

How did you configure Gatsby to use tags? Like [this](https://www.gatsbyjs.org/docs/adding-tags-and-categories-to-blog-posts/)?

**Comment by rolwin100** [comment]
Hi, @dandv  😃 Thanks for the appreciation. That not a problem you filled an issue. Even I was not aware of the discussion being enabled, in fact, I don't know how to enable it 😜. I will figure it out once writing this comment.

Coming to the point about the tags page. Basically you need to write the graphql query to query the tags from md files. Once that is being done you need to write a template for the tag page which is placed in the src/templates folder.  Next, I have created the page for tags in the [gatsby-node.js](https://github.com/rolwin100/rolwinreevan_gatsby_blog/blob/master/gatsby-node.js) file. Hope this clears your queries 😊.
