### ISSUE TITLE
Unable to install the template in windows due directory name length limitation or wrong invalid chracters.

### ISSUE THREAD

**Issue by Abhilash-Chandran** [rolwin100/rolwinreevan_gatsby_blog#2]
Looks like the command `gatsby new rolwinreevan_gatsby_blog https://github.com/rolwin100/rolwinreevan_gatsby_blog` fails in windows 10 maybe due to the length of the filename being created or invalid characters like `?` in the file name. Even normal git clone fails. I tried both in power shell and normal cmd with administrator privilege. 

I am proceeding by simply downloading and extracting. Extracting seems to ignore the `?` in the file name.
```
gatsby new portfolio https://github.com/rolwin100/rolwinreevan_gatsby_blog
info Creating new site from git: https://github.com/rolwin100/rolwinreevan_gatsby_blog.git
Cloning into 'portfolio'...
remote: Enumerating objects: 132, done.
remote: Counting objects: 100% (132/132), done.
remote: Compressing objects: 100% (124/124), done.
remote: Total 132 (delta 4), reused 89 (delta 0), pack-reused 0
Receiving objects: 100% (132/132), 2.80 MiB | 5.58 MiB/s, done.
Resolving deltas: 100% (4/4), done.
fatal: cannot create directory at 'content/2020-04-08-why-I-migrated-my-website-from-worpress-to-gatsby?': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'


 ERROR

Command failed with exit code 128: git clone https://github.com/rolwin100/rolwinreevan_gatsby_blog.git portfolio --recursive --depth=1



  Error: Command failed with exit code 128: git clone https://github.com/rolwin100/rolwinreevan_gatsby_blog.git portfoli  o --recursive --depth=1

  - error.js:56 makeError
    [Anaconda3]/[gatsby-cli]/[execa]/lib/error.js:56:11

  - index.js:114 handlePromise
    [Anaconda3]/[gatsby-cli]/[execa]/index.js:114:26

  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
```

**Comment by rolwin100** [comment]
Hmm I don't think this an issue with the template. You can run this command and check instead git clone https://github.com/rolwin100/rolwinreevan_gatsby_blog.git

This should work @Abhilash-Chandrean

**Comment by Abhilash-Chandran** [comment]
Nope git clone fails as well with the same error. Definitely this is not an issue with the template 😃 . 

But this would stop anyone who wants to get started with the template in windows. Its definitely the `?` in the directory `contents\2020-04-08-why-I-migrated-my-website-from-worpress-to-gatsby?`.  when i downloaded as zip and extracted it simply replaced `?` with `_`. Its a short fall of windows not the template. But just to let you know I created an issue. 

BTW very good responsive template. Will use it and let you know if I find something else. Thank you.

**Comment by rolwin100** [comment]
@Abhilash-Chandran thanks for your concern I'm not sure how to solve your issue. Because I have given a naming to my contents for readability. I will try something out to help you.

I'm happy you liked it but pls give a star and fork it before you use it. That's how you can appreciate my efforts and encourage me to add more features to it.

**Comment by rolwin100** [comment]
This should solve your issue .Pls try to follow this [link](https://github.com/gatsbyjs/gatsby/issues/20003)

**Comment by Abhilash-Chandran** [comment]
> This should solve your issue .Pls try to follow this [link](https://github.com/gatsbyjs/gatsby/issues/20003)

I understand you cannot solve it directly without renaming the directory. I just raised an issue so that others don't get blocked. The link you posted is for WSL and I don't use WSL in my windows and neither for my other node projects. I haven't felt a need for WSL yet. 😉 

That said this is definitely a windows issue. But thought users should be aware of it so that they don't think its an issue with the template. 

For example this is common issue with git clone when the files are created in other os with character s which are not acceptable for windows. e,g, [this](https://stackoverflow.com/questions/47190792/github-clone-fatal-error-cannot-create-directory-at-windows)

Windows has certain reserved string which is not allowed as shown [here](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions).

> @Abhilash-Chandran thanks for your concern I'm not sure how to solve your issue. Because I have given a naming to my contents for readability. I will try something out to help you.
> 
> I'm happy you liked it but pls give a star and fork it before you use it. That's how you can appreciate my efforts and encourage me to add more features to it.

Done 👍 💯 

You can close this issue if you feel so.

**Comment by feederaccount** [comment]
I am also having this issue. Wouldn't the best solution be to remove the `?` from that path? Windows is the most popular OS in the world so I think it's worth working around it rather than having the entire process crash due to nothing more than a question mark in a URL.

**Comment by rolwin100** [comment]
@feederaccount I not sure what question mark you are talking about and the other thing is its gatsby issue not the template issue. So I believe it's better to raise the issue with gatsby.

**Comment by feederaccount** [comment]
@rolwin100 The issue isn't with Gatsby. I got the same error using:

- Gatsby CLI
- Git CLI
- Fork (Git client)

The error was:

```
error: invalid path 'content/2020-04-08-why-I-migrated-my-website-from-worpress-to-gatsby?/gatsby-deploy.png'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

The issue seems to be with `...from-worpress-to-gatsby?/`.

I got around it by downloading it as a ZIP and manually extracting the files.

**Comment by rolwin100** [comment]
@feederaccount you are right sorry for the ? mark at the end didn't notice that till date. Will fix it ASAP within the next 2mins

**Comment by rolwin100** [comment]
pls check now and let me know @feederaccount

**Comment by feederaccount** [comment]
Quick fix :)

I've already got the template working so I don't need to test it. That's probably it fixed though.
